import type { APIRoute } from "astro";
import { buildCareerReport } from "@/lib/cip/career-report";
import { isSameOriginRequest } from "@/lib/security";
import { createServer } from "@/lib/supabase/server";

/**
 * POST /api/report/generate
 *
 * Builds the Career Intelligence Report deterministically from saved analysis,
 * persists it additively as a `career_sources` row (source_type "career_report",
 * trust_state "system_generated" — mirrors how resume_draft is stored), and
 * returns an htmx-friendly confirmation. Matches the briefing/generate flow.
 *
 * The report is assembled, not generated by an LLM: every claim keeps its
 * source status so the page can show a visible confidence label. (§8, §19)
 */
export const POST: APIRoute = async ({ request, cookies }) => {
  if (!isSameOriginRequest(request)) {
    return html('<p class="text-sm text-red-700">Invalid request origin.</p>', 403);
  }

  const supabase = createServer(cookies);
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return html('<p class="text-sm text-red-700">Sign in before generating a report.</p>', 401);
  }

  const report = await buildCareerReport(supabase, user.id);

  // Persist additively. Never overwrite prior reports — additive history is
  // part of the trust model (the user can compare runs over time).
  await supabase.from("career_sources").insert({
    user_id: user.id,
    source_type: "career_report",
    title: "Career Intelligence Report",
    extracted_text: JSON.stringify({ saved_at: new Date().toISOString(), report }),
    trust_state: "system_generated",
  });

  if (report.status === "ready") {
    return html(`
      <div class="rounded-lg border border-[var(--line)] bg-[var(--background)] p-5">
        <p class="text-sm font-semibold text-[var(--accent-strong)]">Career Intelligence Report generated.</p>
        <p class="mt-2 text-sm leading-6 text-[var(--muted)]">Built deterministically from your saved analysis${report.analysisMode ? ` (analysis mode: ${escapeHtml(report.analysisMode)})` : ""}. Every claim carries its evidence status.</p>
        <p class="mt-3 text-sm text-[var(--muted)]">Refresh this page to view the full report.</p>
      </div>
    `);
  }

  // Honest non-ready state: tell the user exactly what's missing and where to go.
  return html(`
    <div class="rounded-lg border border-[var(--line)] bg-[var(--background)] p-5">
      <p class="text-sm font-semibold text-[var(--warning)]">Not enough saved analysis to build a full report yet.</p>
      <p class="mt-2 text-sm leading-6 text-[var(--muted)]">${escapeHtml(report.summary || "Complete intake and evidence analysis first.")}</p>
      <p class="mt-3 text-sm text-[var(--muted)]">Refresh this page, or go to the next step to continue.</p>
    </div>
  `);
};

function html(body: string, status = 200) {
  return new Response(body, {
    status,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
